package com.model.enumerations;

public enum Dependency_Type {

	PRECEDENCE_DEPENDENCY,
	QUEUEING_BUFFER_DEPENDENCY
	,ASYNCHRONOUS_COMMUNICATION_DEPENDENCY
	,TIME_TRIGGERED_COMMUNICATION_DEPENDENCY
	,RESOURCE_DEPENDENCY
	,BLACK_BOARD_BUFFER_DEPENDENCY
}
