package com.model.enumerations;

/**
 * 
 * @author Jugurtha
 * Types of objects that can be in the system
 */
public enum Objects_Type {
	
	BUFFER_OBJECT_TYPE,
	PROCESSOR_OBJECT_TYPE,
	CACHE_BLOCK_OBJECT_TYPE,
	CACHE_OBJECT_TYPE,
	TASK_OBJECT_TYPE,
	RESOURCE_OBJECT_TYPE,
	ADDRESS_SPACE_OBJECT_TYPE,
	MESSAGE_OBJECT_TYPE,
	STATE__OBJECT_TYPE,
	TRANSITION_OBJECT_TYPE,
	STATEMENT__OBJECT_TYPE,
	EXPRESSION_OBJECT_TYPE,
	SYNCHRONIZATION_OBJECT_TYPE,
	SECTION_OBJECT_TYPE,
	NETWORK_OBJECT_TYPE,
	CONNEXION_OBJECT_TYPE,
	CORE_OBJECT_TYPE,
	EVENT_ANALYZER_TYPE,
	DEPLOYEMENT_TYPE,
	CFG_NODE_OBJECT_TYPE,
	CFG_EDGE_OBJECT_TYPE,
	CFG__OBJECT_TYPE,
	CACHE_ACCESS_PROFILE_OBJECT_TYPE

}
